on:
  push:
    branches:
    - docker

name: build_on_docker_branch
runs-on: ubuntu:latest
runs:
  using: 'docker'
  image: 'Dockerfile'
jobs:
  just_do_something_job:
    steps:
    - run: 'echo hi'
