name: github_actions_experimentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@v1

    - name: install bats
      run : npm install -g bats

    - name: run bats
      run: bats -v
